sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - ruby-head
  - jruby-9.1.5.0
  - jruby-head
  - rubinius-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rubinius-3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.14.3
